version: '3.8'
services:
  start:
    build:
      context: .
    ports:
      - 3000:3000
  test:
    build:
      context: .
    entrypoint:
      - make
      - test
      - test-ui
  build:
    build:
      context: .
    entrypoint:
      - make
    volumes:
      - .:/app
