version: '3.0'
services:
  dev: &base
    image: node
    user: $UID:$GID
    volumes:
    - .:/code
    working_dir: /code
    environment:
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/code/node_modules/.bin"
    entrypoint:
    - /usr//bin/tail
    - -f
    - /etc/hosts

  test:
    <<: *base
    working_dir: /code
    entrypoint:
    - make
    - test

  build:
    image: node
    user: $UID:$GID
    working_dir: /code
    volumes:
    - .:/code
    entrypoint:
    - make

  run:
    build: .
    ports:
    - "8000:8000"
    user: $UID:$GID
