version: '3.8'
services:
  start:
    build:
      context: .
    ports:
      - 3000:3000
    user: $UID:$GID
  test:
    build:
      context: .
    entrypoint:
      - make
      - test
      - test-ui
    user: $UID:$GID
  build:
    build:
      context: .
    entrypoint:
      - make
    user: $UID:$GID
    volumes:
      - .:/app
