openapi: 3.0.0
info:
  title: customer
  version: '1.0'
servers:
  - url: 'https://api.example.com'
paths:
  '/customers/{customer_id}':
    parameters:
      - schema:
          type: integer
        name: customer_id
        in: path
        required: true
    get:
      summary: customer
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  customer_id:
                    type: integer
                  customer_name:
                    type: string
      operationId: get-customers-customer_id
      description: Retrieve a specific customer by ID
components:
  schemas: {}