export const TOOGLE_MENU = 'TOOGLE_MENU';
export const SET_VALIDATION_RESULTS = 'SET_VALIDATION_RESULTS';
export const SET_VALIDATION_IN_PROGRESS = 'SET_VALIDATION_IN_PROGRESS';
export const SET_DOCUMENT_TEXT = 'SET_DOCUMENT_TEXT';
export const FOCUS_DOCUMENT_LINE = 'FOCUS_DOCUMENT_LINE';
