#!/usr/bin/env node
const mergeYaml = require('merge-yaml');
const YAML = require('yaml')

const all_rules = mergeYaml([
'rules/metadata.yml',
'rules/numbers.yml',
'rules/pagination.yml',
'rules/patch.yml',
'rules/problem.yml',
'rules/ratelimit.yml',
]);
const out = YAML.stringify(all_rules);
console.log(out);
