#!/usr/bin/env node
const mergeYaml = require('merge-yaml');
const YAML = require('yaml');
const glob = require('glob');

const rule_files = glob.sync("rules/*.yml");
const all_rules = mergeYaml(rule_files);
const out = YAML.stringify(all_rules);
console.log(out);
