#!/usr/bin/env node
const mergeYaml = require('merge-yaml');
const YAML = require('yaml');

const rule_files = process.argv.slice(2);
const all_rules = mergeYaml(rule_files);
const out = YAML.stringify(all_rules);
console.log(out);
